### ISSUE TITLE
Please add contribution guidelines 

### ISSUE THREAD

**Issue by programmer290399** [AakashKumarNain/annotated_research_papers#4]
I would really love to contribute papers to this repository  , so It'd be really helpful if the repo had clear contribution guidelines which I couldn't find. Please add a section mentioning the guidelines in the readme. :slightly_smiling_face:

**Comment by AakashKumarNain** [comment]
Contributions in this case is really hard. For example, if you submit a paper with annotations, I need to read the paper as well the annotations to make sure that the interpretation is correct, which sadly I can't do atm. Though I am looking for some other ways of contributions and will update them here if they seem feasible options.
