### ISSUE TITLE
Recommended way - To read the given papers

### ISSUE THREAD

**Issue by namanphy** [AakashKumarNain/annotated_research_papers#7]
Hey Aakash,

To put it plainly, I'd like to know how to read your annotated papers in the best possible way. 
I'm referring to whether one should read the relevant paper first and then move on to your version, or whether one should start reading the annotated paper right away and add notes alongside if necessary.

As this is subjective, I'm not sure if this is the right question to ask, or if I should just go ahead and try both. Any thoughts?

**Comment by AakashKumarNain** [comment]
If you want to read quickly:
1. Read the abstract
2. Read the `summary` section in the end
3. Go through the `fig` and equations after reading the summary for each page
4. Check any other details highlighted in the annotated sections
